version: "3.9"

services:
  redis:
    image: redis:7.4-alpine
    ports:
      - "127.0.0.1:6379:6379"

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    environment:
      CLICKHOUSE_DB: nimbus
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"

  control-plane:
    build: .
    command: ["uvicorn", "nimbus.control_plane.app:create_app", "--factory", "--host", "0.0.0.0", "--port", "8000"]
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    environment:
      NIMBUS_GITHUB_APP_ID: ${NIMBUS_GITHUB_APP_ID:-1}
      NIMBUS_GITHUB_APP_PRIVATE_KEY: ${NIMBUS_GITHUB_APP_PRIVATE_KEY:-stub}
      NIMBUS_GITHUB_APP_INSTALLATION_ID: ${NIMBUS_GITHUB_APP_INSTALLATION_ID:-1}
      NIMBUS_GITHUB_WEBHOOK_SECRET: ${NIMBUS_GITHUB_WEBHOOK_SECRET:-secret}
      NIMBUS_REDIS_URL: redis://redis:6379/0
      NIMBUS_DATABASE_URL: sqlite+aiosqlite:///data/control.db
      NIMBUS_JWT_SECRET: ${NIMBUS_JWT_SECRET:-jwt-secret}
      NIMBUS_AGENT_TOKEN_SECRET: ${NIMBUS_AGENT_TOKEN_SECRET:-agent-secret}
      NIMBUS_CACHE_SHARED_SECRET: ${NIMBUS_CACHE_SHARED_SECRET:-cache-secret}
      NIMBUS_CACHE_TOKEN_TTL: ${NIMBUS_CACHE_TOKEN_TTL:-3600}
      NIMBUS_PUBLIC_BASE_URL: http://control-plane:8000
      NIMBUS_AGENT_TOKEN_RATE_LIMIT: ${NIMBUS_AGENT_TOKEN_RATE_LIMIT:-15}
      NIMBUS_AGENT_TOKEN_RATE_INTERVAL: ${NIMBUS_AGENT_TOKEN_RATE_INTERVAL:-60}
      NIMBUS_LOG_LEVEL: ${NIMBUS_LOG_LEVEL:-INFO}
      NIMBUS_METADATA_SINK_URL: http://logging-pipeline:8090
    depends_on:
      - redis
      - clickhouse
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - control-data:/app/data

  cache-proxy:
    build: .
    command: ["uvicorn", "nimbus.cache_proxy.app:create_app", "--factory", "--host", "0.0.0.0", "--port", "8080"]
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    environment:
      NIMBUS_CACHE_SHARED_SECRET: ${NIMBUS_CACHE_SHARED_SECRET:-cache-secret}
      NIMBUS_CACHE_STORAGE_PATH: /data/cache
      NIMBUS_CACHE_METRICS_DB: /data/cache/cache_metrics.db
      NIMBUS_LOG_LEVEL: ${NIMBUS_LOG_LEVEL:-INFO}
    volumes:
      - cache-data:/data/cache
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - control-plane

  docker-cache:
    build: .
    command: ["uvicorn", "nimbus.docker_cache.app:create_app", "--factory", "--host", "0.0.0.0", "--port", "5001"]
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    environment:
      NIMBUS_CACHE_SHARED_SECRET: ${NIMBUS_CACHE_SHARED_SECRET:-cache-secret}
      NIMBUS_DOCKER_CACHE_STORAGE_PATH: /data/docker-cache/blobs
      NIMBUS_DOCKER_CACHE_UPLOAD_PATH: /data/docker-cache/uploads
      NIMBUS_DOCKER_CACHE_DB_PATH: /data/docker-cache/metadata.db
      NIMBUS_DOCKER_CACHE_MAX_BYTES: ${NIMBUS_DOCKER_CACHE_MAX_BYTES:-0}
      NIMBUS_LOG_LEVEL: ${NIMBUS_LOG_LEVEL:-INFO}
    volumes:
      - docker-cache-data:/data/docker-cache
    ports:
      - "127.0.0.1:5001:5001"
    depends_on:
      - control-plane
      - cache-proxy

  web:
    image: node:20-alpine
    working_dir: /app
    entrypoint: ["sh", "-c", "npm install && npm run dev -- --host 0.0.0.0"]
    user: "node"
    volumes:
      - ./web:/app
    environment:
      VITE_DEFAULT_CONTROL_PLANE_URL: http://control-plane:8000
      VITE_DEFAULT_LOGGING_URL: http://logging-pipeline:8090
    ports:
      - "127.0.0.1:5173:5173"
    depends_on:
      - control-plane

  logging-pipeline:
    build: .
    command: ["uvicorn", "nimbus.logging_pipeline.app:create_app", "--factory", "--host", "0.0.0.0", "--port", "8090"]
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    environment:
      NIMBUS_CLICKHOUSE_URL: http://clickhouse:8123
      NIMBUS_CLICKHOUSE_DATABASE: nimbus
      NIMBUS_CLICKHOUSE_TABLE: ci_logs
      NIMBUS_LOG_LEVEL: ${NIMBUS_LOG_LEVEL:-INFO}
    depends_on:
      - clickhouse
    ports:
      - "127.0.0.1:8090:8090"

  host-agent:
    build: .
    command: ["python", "-m", "nimbus.host_agent.main"]
    environment:
      NIMBUS_AGENT_ID: ${NIMBUS_AGENT_ID:-agent-1}
      NIMBUS_CONTROL_PLANE_URL: http://control-plane:8000
      NIMBUS_CONTROL_PLANE_TOKEN: ${NIMBUS_CONTROL_PLANE_TOKEN:-set-agent-token}
      NIMBUS_KERNEL_IMAGE: /artifacts/vmlinux
      NIMBUS_ROOTFS_IMAGE: /artifacts/rootfs.ext4
      NIMBUS_FC_BIN: /artifacts/firecracker
      NIMBUS_CACHE_PROXY_URL: http://cache-proxy:8080
      NIMBUS_LOG_SINK_URL: http://logging-pipeline:8090
      NIMBUS_CACHE_TOKEN_SECRET: ${NIMBUS_CACHE_SHARED_SECRET:-cache-secret}
      NIMBUS_CACHE_TOKEN_VALUE: ${NIMBUS_CACHE_TOKEN_VALUE:-}
      NIMBUS_JOB_TIMEOUT: ${NIMBUS_JOB_TIMEOUT:-3600}
      NIMBUS_AGENT_LEASE_RETRIES: ${NIMBUS_AGENT_LEASE_RETRIES:-5}
      NIMBUS_AGENT_LEASE_RETRY_BASE: ${NIMBUS_AGENT_LEASE_RETRY_BASE:-1.0}
      NIMBUS_AGENT_LEASE_RETRY_MAX: ${NIMBUS_AGENT_LEASE_RETRY_MAX:-10.0}
      NIMBUS_LOG_LEVEL: ${NIMBUS_LOG_LEVEL:-INFO}
    volumes:
      - ./artifacts:/artifacts:ro
      - /dev/kvm:/dev/kvm
    depends_on:
      - control-plane
      - cache-proxy
    profiles:
      - agent
    privileged: true

  ai-eval-runner:
    build:
      context: ./containers/ai-eval-runner
    image: nimbus/ai-eval-runner

volumes:
  clickhouse-data:
  control-data:
  cache-data:
  docker-cache-data:
