apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nimbus.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nimbus.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nimbus.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nimbus.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: control-plane
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
        - name: cache-proxy
          image: {{ .Values.cacheProxy.image }}
          ports:
            - containerPort: {{ .Values.cacheProxy.port }}
        - name: logging-pipeline
          image: {{ .Values.loggingPipeline.image }}
          ports:
            - containerPort: {{ .Values.loggingPipeline.port }}
