name: Eval Suite

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          pip install -r requirements.txt
      - name: Run evaluation
        run: |
          python scripts/run_eval.py --suite smoke
